GET http://localhost:7000/api/query/post

###
GET http://localhost:7000/api/post/getPostBySlug/kham-pha-vung-dat-nui-lua-nicaragua
###
GET http://localhost:7000/api/post/lastPost

###
GET http://localhost:7000/api/post/getAllPost

###
GET http://localhost:7000/api/post/getPostByCategory/the-gioi

###
GET http://localhost:7000/api/post/getListCategory

###
GET http://localhost:7000/api/post/getAllPostByCategory/thoi-su